import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster"

import localFont from 'next/font/local'
import "./globals.css";
import SideBar from "@/components/Sidebar";
import Providers from "@/components/Providers";
import { getServerSession } from "next-auth";

const font = localFont({ src: [
  {
    path: './fonts/Mont-Bold.ttf',
    weight: 'bold',
  },
  {
    path: './fonts/Mont-Semibold.ttf',
    weight: '500',
  },

  {
    path: './fonts/Mont-Regular.ttf',
    weight: '600',
  },
  {
    path: './fonts/Mont-ExtraLight.ttf',
    weight: '400',
  },
] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers session={session}>
        <div className="flex flex-col sm:flex-row ">
          <SideBar />
          <div className="w-full flex flex-col">
            <div className=" 2xl:h-[90px] h-[20px] sm:h-[60px]">
            </div>
            <main className="w-full">{children}</main>
          </div>
        </div>
        <Toaster />

        </Providers>
      </body>
    </html>
  );
}
